# Generated by Django 5.2.5 on 2025-09-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_loan_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_credit_related',
            field=models.BooleanField(default=False, verbose_name='Связано с кредитами'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.loan', verbose_name='Связанный кредит'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('credit', 'Потребительский кредит'), ('mortgage', 'Ипотека'), ('loan', 'Заём')], max_length=20, verbose_name='Тип кредита'),
        ),
    ]
